version: '3.7'

services:
  app:
    build: SpotifyAPI.API/
    ports:
      - "8000:80"
    depends_on:
      - minio
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"

  minio:
    image: minio/minio:latest
    container_name: minio-s3
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:~/Projects/minio

volumes:
  minio-data:
    name: minio-data